### ISSUE TITLE
关于绘制文本时文本属性的问题

### ISSUE THREAD

**Issue by M-Nemo** [chenshenhai/discuss#9]
绘制文本时看到文档中文本只提供了
`
    color,
    fontSize,
    textAlign,
    bgColor,
    borderRadius,
    borderWidth,
    borderColor,
`
几个基本属性，没有提供fontweight属性，但是看到studio中的demo是有文字加粗效果的，想知道如何实现的，因为现在想加一些文本属性

**Comment by chenshenhai** [comment]
@M-Nemo  您好，idraw.js自带的text元素目前不支持字体加粗，但是你可以渲染html元素基于CSS来加粗字体。可以参考这个文档 https://idraw.js.org/docs/en/element/html.html#complete-data-example 

最后，关于idrawjs的问题讨论，麻烦移步到 https://github.com/idrawjs/idraw/issues

**Comment by M-Nemo** [comment]
这是来自QQ邮箱的自动回复邮件。您好，我最近正在忙碌中，无法亲自回复您的邮件。我将在忙碌束后，尽快给您回复。
